import { hashSync } from "bcryptjs";

import type { Alert } from "../../../features/alerts/domain/alert.entity";
import type { AuditLog } from "../../../features/audit/domain/audit-log.entity";
import type { User } from "../../../features/auth/domain/user.entity";
import type { EmailMessage } from "../../../features/emails/domain/email-message.entity";
import type { GmailAccount } from "../../../features/gmail-accounts/domain/gmail-account.entity";
import type { GmailOAuthToken } from "../../../features/gmail-accounts/domain/gmail-oauth-token.entity";
import type { GmailSyncLog } from "../../../features/gmail-accounts/domain/gmail-sync-log.entity";
import type { AutomationRule } from "../../../features/rules/domain/automation-rule.entity";
import type { SenderProfile } from "../../../features/senders/domain/sender-profile.entity";
import type { WorkspaceSettings } from "../../../features/settings/domain/workspace-settings.entity";
import type { Workspace } from "../../../features/workspace/domain/workspace.entity";

export interface InMemoryDatabase {
  users: User[];
  workspaces: Workspace[];
  workspaceSettings: Record<string, WorkspaceSettings>;
  gmailAccounts: GmailAccount[];
  gmailOAuthTokens: GmailOAuthToken[];
  gmailSyncLogs: GmailSyncLog[];
  emails: EmailMessage[];
  alerts: Alert[];
  senders: SenderProfile[];
  rules: AutomationRule[];
  auditLogs: AuditLog[];
}

const now = "2026-06-15T10:00:00.000Z";
const workspaceId = "workspace_demo";
const ownerId = "user_owner_demo";
const primaryGmailId = "gmail_primary_demo";
const billingGmailId = "gmail_billing_demo";
const securityEmailId = "email_security_demo";
const invoiceEmailId = "email_invoice_demo";
const legalEmailId = "email_legal_demo";

export function createSeededInMemoryDatabase(): InMemoryDatabase {
  return {
    users: [
      {
        id: ownerId,
        workspaceId,
        name: "Usuario Demo",
        email: "owner@autogmail.local",
        passwordHash: hashSync("Password123!", 10),
        role: "OWNER",
        createdAt: "2026-06-01T08:00:00.000Z",
      },
    ],
    workspaces: [
      {
        id: workspaceId,
        name: "Auto-Gmail-code Demo",
        ownerId,
        plan: "starter",
        createdAt: "2026-06-01T08:00:00.000Z",
      },
    ],
    workspaceSettings: {},
    gmailAccounts: [
      {
        id: primaryGmailId,
        workspaceId,
        emailAddress: "principal.demo@gmail.com",
        status: "CONNECTED",
        lastSyncAt: "2026-06-15T09:55:00.000Z",
        watchExpiration: "2026-06-22T09:55:00.000Z",
        totalMessages: 1264,
        historyId: null,
        grantedScopes: [
          "https://www.googleapis.com/auth/gmail.readonly",
          "https://www.googleapis.com/auth/gmail.modify",
        ],
        errorMessage: null,
        createdAt: "2026-06-02T09:30:00.000Z",
      },
      {
        id: billingGmailId,
        workspaceId,
        emailAddress: "facturacion.demo@gmail.com",
        status: "SYNCING",
        lastSyncAt: "2026-06-15T09:40:00.000Z",
        watchExpiration: "2026-06-22T09:40:00.000Z",
        totalMessages: 842,
        historyId: null,
        grantedScopes: ["https://www.googleapis.com/auth/gmail.readonly"],
        errorMessage: null,
        createdAt: "2026-06-03T11:10:00.000Z",
      },
      {
        id: "gmail_reconnect_demo",
        workspaceId,
        emailAddress: "alertas.demo@gmail.com",
        status: "RECONNECT_REQUIRED",
        lastSyncAt: "2026-06-13T18:20:00.000Z",
        watchExpiration: null,
        totalMessages: 304,
        historyId: null,
        grantedScopes: ["https://www.googleapis.com/auth/gmail.readonly"],
        errorMessage: "El refresh token fue revocado por Google.",
        createdAt: "2026-06-05T14:45:00.000Z",
      },
    ],
    gmailOAuthTokens: [],
    gmailSyncLogs: [
      {
        id: "sync_log_primary_demo",
        workspaceId,
        gmailAccountId: primaryGmailId,
        status: "COMPLETED",
        startedAt: "2026-06-15T09:54:30.000Z",
        finishedAt: "2026-06-15T09:55:00.000Z",
        fetchedMessages: 25,
        createdMessages: 4,
        updatedMessages: 0,
        errorMessage: null,
        metadata: {
          mode: "seed",
          messagesTotal: 1264,
        },
      },
    ],
    emails: [
      {
        id: securityEmailId,
        workspaceId,
        gmailAccountId: primaryGmailId,
        gmailMessageId: "gmail_msg_001",
        threadId: "thread_security_001",
        accountEmail: "principal.demo@gmail.com",
        fromEmail: "security@google.com",
        fromName: "Google",
        fromDomain: "google.com",
        toEmails: ["principal.demo@gmail.com"],
        subject: "Nuevo inicio de sesion",
        snippet: "Detectamos un nuevo inicio de sesion en tu cuenta.",
        bodyHtml:
          "<p>Detectamos un nuevo inicio de sesion desde un dispositivo no reconocido.</p>",
        bodyText: "Detectamos un nuevo inicio de sesion desde un dispositivo no reconocido.",
        receivedAt: "2026-06-15T09:50:00.000Z",
        labelIds: ["INBOX", "IMPORTANT"],
        hasAttachments: false,
        attachments: [],
        isRead: false,
        isSpam: false,
        isImportant: true,
        reviewedAt: null,
        gmailUrl: "https://mail.google.com/mail/u/0/#inbox/gmail_msg_001",
        classification: {
          id: "classification_security_demo",
          emailMessageId: securityEmailId,
          primaryCategory: "SECURITY",
          secondaryCategories: ["IMPORTANT"],
          importanceScore: 92,
          spamScore: 4,
          riskScore: 48,
          securityScore: 96,
          actionRequired: true,
          explanation:
            "El correo contiene senales de acceso de seguridad y requiere revision del usuario.",
          createdAt: "2026-06-15T09:51:00.000Z",
          updatedAt: "2026-06-15T09:51:00.000Z",
        },
        actionHistory: [
          {
            id: "history_security_001",
            actor: "SYSTEM",
            action: "EMAIL_CLASSIFIED",
            description: "Correo clasificado como seguridad.",
            createdAt: "2026-06-15T09:51:00.000Z",
          },
        ],
      },
      {
        id: invoiceEmailId,
        workspaceId,
        gmailAccountId: billingGmailId,
        gmailMessageId: "gmail_msg_002",
        threadId: "thread_invoice_001",
        accountEmail: "facturacion.demo@gmail.com",
        fromEmail: "billing@stripe.com",
        fromName: "Stripe",
        fromDomain: "stripe.com",
        toEmails: ["facturacion.demo@gmail.com"],
        subject: "Factura mensual disponible",
        snippet: "Tu factura de junio ya esta disponible para revision.",
        bodyHtml: "<p>La factura mensual de Auto-Gmail-code esta disponible.</p>",
        bodyText: "La factura mensual de Auto-Gmail-code esta disponible.",
        receivedAt: "2026-06-15T08:35:00.000Z",
        labelIds: ["INBOX"],
        hasAttachments: true,
        attachments: [
          {
            id: "attachment_invoice_pdf",
            filename: "invoice-june.pdf",
            mimeType: "application/pdf",
            sizeBytes: 184320,
          },
        ],
        isRead: true,
        isSpam: false,
        isImportant: true,
        reviewedAt: null,
        gmailUrl: "https://mail.google.com/mail/u/1/#inbox/gmail_msg_002",
        classification: {
          id: "classification_invoice_demo",
          emailMessageId: invoiceEmailId,
          primaryCategory: "FINANCIAL",
          secondaryCategories: ["IMPORTANT"],
          importanceScore: 84,
          spamScore: 2,
          riskScore: 18,
          securityScore: 12,
          actionRequired: true,
          explanation:
            "Correo financiero con adjunto de factura y posible accion pendiente de pago.",
          createdAt: "2026-06-15T08:36:00.000Z",
          updatedAt: "2026-06-15T08:36:00.000Z",
        },
        actionHistory: [
          {
            id: "history_invoice_001",
            actor: "SYSTEM",
            action: "EMAIL_CLASSIFIED",
            description: "Correo clasificado como financiero.",
            createdAt: "2026-06-15T08:36:00.000Z",
          },
        ],
      },
      {
        id: legalEmailId,
        workspaceId,
        gmailAccountId: primaryGmailId,
        gmailMessageId: "gmail_msg_003",
        threadId: "thread_legal_001",
        accountEmail: "principal.demo@gmail.com",
        fromEmail: "notificaciones@juzgado.example",
        fromName: "Juzgado",
        fromDomain: "juzgado.example",
        toEmails: ["principal.demo@gmail.com"],
        subject: "Notificacion judicial pendiente",
        snippet: "Se ha emitido una notificacion que requiere revision.",
        bodyHtml: "<p>Existe una notificacion judicial pendiente de lectura.</p>",
        bodyText: "Existe una notificacion judicial pendiente de lectura.",
        receivedAt: "2026-06-14T16:15:00.000Z",
        labelIds: ["INBOX", "IMPORTANT"],
        hasAttachments: true,
        attachments: [
          {
            id: "attachment_legal_pdf",
            filename: "notificacion.pdf",
            mimeType: "application/pdf",
            sizeBytes: 293120,
          },
        ],
        isRead: false,
        isSpam: false,
        isImportant: true,
        reviewedAt: null,
        gmailUrl: null,
        classification: {
          id: "classification_legal_demo",
          emailMessageId: legalEmailId,
          primaryCategory: "LEGAL",
          secondaryCategories: ["IMPORTANT", "REVIEW"],
          importanceScore: 95,
          spamScore: 8,
          riskScore: 72,
          securityScore: 36,
          actionRequired: true,
          explanation:
            "El asunto y dominio sugieren una notificacion legal con fecha critica.",
          createdAt: "2026-06-14T16:16:00.000Z",
          updatedAt: "2026-06-14T16:16:00.000Z",
        },
        actionHistory: [
          {
            id: "history_legal_001",
            actor: "SYSTEM",
            action: "ALERT_CREATED",
            description: "Se genero alerta por posible notificacion legal.",
            createdAt: "2026-06-14T16:16:00.000Z",
          },
        ],
      },
      {
        id: "email_promo_demo",
        workspaceId,
        gmailAccountId: primaryGmailId,
        gmailMessageId: "gmail_msg_004",
        threadId: "thread_promo_001",
        accountEmail: "principal.demo@gmail.com",
        fromEmail: "news@store.example",
        fromName: "Store News",
        fromDomain: "store.example",
        toEmails: ["principal.demo@gmail.com"],
        subject: "Promocion limitada",
        snippet: "Obtenga descuento especial durante las proximas 24 horas.",
        bodyHtml: "<p>Promocion de temporada con descuento.</p>",
        bodyText: "Promocion de temporada con descuento.",
        receivedAt: "2026-06-13T12:00:00.000Z",
        labelIds: ["CATEGORY_PROMOTIONS"],
        hasAttachments: false,
        attachments: [],
        isRead: true,
        isSpam: false,
        isImportant: false,
        reviewedAt: "2026-06-13T13:05:00.000Z",
        gmailUrl: null,
        classification: {
          id: "classification_promo_demo",
          emailMessageId: "email_promo_demo",
          primaryCategory: "PROMOTIONS",
          secondaryCategories: [],
          importanceScore: 18,
          spamScore: 22,
          riskScore: 10,
          securityScore: 3,
          actionRequired: false,
          explanation: "Promocion comercial sin indicadores de riesgo alto.",
          createdAt: "2026-06-13T12:01:00.000Z",
          updatedAt: "2026-06-13T12:01:00.000Z",
        },
        actionHistory: [],
      },
    ],
    alerts: [
      {
        id: "alert_security_demo",
        workspaceId,
        gmailAccountId: primaryGmailId,
        emailMessageId: securityEmailId,
        type: "SECURITY_LOGIN",
        severity: "HIGH",
        title: "Nuevo inicio de sesion detectado",
        description: "Google reporto un inicio de sesion en un dispositivo no reconocido.",
        status: "NEW",
        recommendedAction: "Revisar el correo y validar si el acceso fue legitimo.",
        createdAt: "2026-06-15T09:51:00.000Z",
        resolvedAt: null,
      },
      {
        id: "alert_legal_demo",
        workspaceId,
        gmailAccountId: primaryGmailId,
        emailMessageId: legalEmailId,
        type: "LEGAL_NOTICE",
        severity: "CRITICAL",
        title: "Notificacion legal pendiente",
        description: "Correo legal con alto score de importancia y riesgo.",
        status: "NEW",
        recommendedAction: "Abrir el correo y revisar vencimientos o acciones requeridas.",
        createdAt: "2026-06-14T16:16:00.000Z",
        resolvedAt: null,
      },
      {
        id: "alert_reconnect_demo",
        workspaceId,
        gmailAccountId: "gmail_reconnect_demo",
        emailMessageId: null,
        type: "ACCOUNT_RECONNECT_REQUIRED",
        severity: "MEDIUM",
        title: "Cuenta Gmail requiere reconexion",
        description: "El acceso OAuth de alertas.demo@gmail.com necesita renovarse.",
        status: "SEEN",
        recommendedAction: "Iniciar el flujo OAuth de reconexion.",
        createdAt: "2026-06-13T18:21:00.000Z",
        resolvedAt: null,
      },
    ],
    senders: [
      {
        id: "sender_google_demo",
        workspaceId,
        email: "security@google.com",
        domain: "google.com",
        displayName: "Google",
        totalMessages: 48,
        lastSeenAt: "2026-06-15T09:50:00.000Z",
        trustScore: 88,
        riskScore: 20,
        category: "SECURITY",
        status: "TRUSTED",
      },
      {
        id: "sender_stripe_demo",
        workspaceId,
        email: "billing@stripe.com",
        domain: "stripe.com",
        displayName: "Stripe",
        totalMessages: 21,
        lastSeenAt: "2026-06-15T08:35:00.000Z",
        trustScore: 82,
        riskScore: 12,
        category: "FINANCIAL",
        status: "TRUSTED",
      },
      {
        id: "sender_legal_demo",
        workspaceId,
        email: "notificaciones@juzgado.example",
        domain: "juzgado.example",
        displayName: "Juzgado",
        totalMessages: 3,
        lastSeenAt: "2026-06-14T16:15:00.000Z",
        trustScore: 52,
        riskScore: 64,
        category: "LEGAL",
        status: "NORMAL",
      },
      {
        id: "sender_store_demo",
        workspaceId,
        email: "news@store.example",
        domain: "store.example",
        displayName: "Store News",
        totalMessages: 68,
        lastSeenAt: "2026-06-13T12:00:00.000Z",
        trustScore: 35,
        riskScore: 22,
        category: "PROMOTIONS",
        status: "NORMAL",
      },
    ],
    rules: [
      {
        id: "rule_google_security_demo",
        workspaceId,
        name: "Google seguridad",
        description: "Clasifica correos de seguridad de Google como prioridad alta.",
        conditions: [
          {
            id: "condition_google_domain",
            field: "fromDomain",
            operator: "equals",
            value: "google.com",
          },
          {
            id: "condition_security_subject",
            field: "subject",
            operator: "contains",
            value: "inicio de sesion",
          },
        ],
        actions: [
          {
            id: "action_assign_security",
            type: "assignCategory",
            value: "SECURITY",
          },
          {
            id: "action_mark_important",
            type: "markImportant",
            value: true,
          },
        ],
        priority: 10,
        enabled: true,
        timesApplied: 12,
        createdAt: "2026-06-04T10:00:00.000Z",
        updatedAt: "2026-06-04T10:00:00.000Z",
      },
      {
        id: "rule_financial_attachments_demo",
        workspaceId,
        name: "Facturas con adjunto",
        description: "Marca correos financieros con adjuntos para revision.",
        conditions: [
          {
            id: "condition_has_attachment",
            field: "hasAttachment",
            operator: "equals",
            value: true,
          },
          {
            id: "condition_billing_domain",
            field: "fromDomain",
            operator: "contains",
            value: "stripe",
          },
        ],
        actions: [
          {
            id: "action_assign_financial",
            type: "assignCategory",
            value: "FINANCIAL",
          },
          {
            id: "action_mark_review",
            type: "markReview",
            value: true,
          },
        ],
        priority: 20,
        enabled: true,
        timesApplied: 8,
        createdAt: "2026-06-06T15:30:00.000Z",
        updatedAt: "2026-06-06T15:30:00.000Z",
      },
    ],
    auditLogs: [
      {
        id: "audit_login_demo",
        workspaceId,
        userId: ownerId,
        action: "AUTH_LOGIN",
        entityType: "User",
        entityId: ownerId,
        description: "Usuario demo inicio sesion.",
        ip: "127.0.0.1",
        metadata: {},
        createdAt: now,
      },
      {
        id: "audit_gmail_connected_demo",
        workspaceId,
        userId: ownerId,
        action: "GMAIL_CONNECTED",
        entityType: "GmailAccount",
        entityId: primaryGmailId,
        description: "Cuenta principal.demo@gmail.com conectada mediante OAuth.",
        ip: "127.0.0.1",
        metadata: { scopes: ["gmail.readonly", "gmail.modify"] },
        createdAt: "2026-06-02T09:30:00.000Z",
      },
      {
        id: "audit_classification_demo",
        workspaceId,
        userId: null,
        action: "EMAIL_CLASSIFIED",
        entityType: "EmailMessage",
        entityId: securityEmailId,
        description: "Sistema clasifico correo como SECURITY.",
        ip: null,
        metadata: { primaryCategory: "SECURITY", securityScore: 96 },
        createdAt: "2026-06-15T09:51:00.000Z",
      },
    ],
  };
}
