export const openApiDocument = {
  openapi: "3.0.3",
  info: {
    title: "Auto-Gmail-code API",
    version: "0.1.0",
    description:
      "Backend API para conectar Gmail via OAuth, sincronizar correos, clasificarlos y operar alertas, reglas, remitentes, analitica y auditoria.",
  },
  servers: [{ url: "/api" }],
  security: [{ bearerAuth: [] }],
  components: {
    securitySchemes: {
      bearerAuth: {
        type: "http",
        scheme: "bearer",
        bearerFormat: "JWT",
      },
    },
  },
  paths: {
    "/health": { get: { security: [], summary: "Healthcheck" } },
    "/auth/register": { post: { security: [], summary: "Registrar usuario propietario" } },
    "/auth/login": { post: { security: [], summary: "Iniciar sesion" } },
    "/auth/logout": { post: { summary: "Cerrar sesion" } },
    "/auth/me": { get: { summary: "Usuario autenticado" } },
    "/workspaces/current": {
      get: { summary: "Obtener workspace actual" },
      patch: { summary: "Actualizar workspace actual" },
    },
    "/gmail/accounts": { get: { summary: "Listar cuentas Gmail" } },
    "/gmail/oauth/start": { post: { summary: "Iniciar OAuth Gmail" } },
    "/gmail/oauth/status": { get: { summary: "Consultar estado OAuth Gmail" } },
    "/gmail/oauth/callback": {
      get: {
        security: [],
        summary: "Callback OAuth Gmail",
        description:
          "Intercambia code por tokens, guarda credenciales cifradas, crea o actualiza cuenta Gmail y sincroniza mensajes recientes.",
      },
    },
    "/gmail/accounts/{id}/sync": { post: { summary: "Sincronizar Gmail manualmente" } },
    "/gmail/accounts/{id}/reconnect": { post: { summary: "Reconectar Gmail" } },
    "/gmail/accounts/{id}": { delete: { summary: "Desconectar Gmail" } },
    "/emails": {
      get: {
        summary: "Bandeja unificada",
        parameters: [
          { name: "page", in: "query", schema: { type: "integer", default: 1 } },
          { name: "limit", in: "query", schema: { type: "integer", default: 25 } },
          { name: "search", in: "query", schema: { type: "string" } },
          { name: "gmailAccountId", in: "query", schema: { type: "string" } },
          { name: "fromEmail", in: "query", schema: { type: "string" } },
          { name: "fromDomain", in: "query", schema: { type: "string" } },
          { name: "category", in: "query", schema: { type: "string" } },
          { name: "isImportant", in: "query", schema: { type: "boolean" } },
          { name: "isSpam", in: "query", schema: { type: "boolean" } },
          { name: "actionRequired", in: "query", schema: { type: "boolean" } },
          { name: "hasAttachments", in: "query", schema: { type: "boolean" } },
          { name: "isRead", in: "query", schema: { type: "boolean" } },
          { name: "minImportanceScore", in: "query", schema: { type: "number" } },
          { name: "minRiskScore", in: "query", schema: { type: "number" } },
          { name: "minSecurityScore", in: "query", schema: { type: "number" } },
          { name: "dateFrom", in: "query", schema: { type: "string", format: "date-time" } },
          { name: "dateTo", in: "query", schema: { type: "string", format: "date-time" } },
          { name: "sortBy", in: "query", schema: { type: "string" } },
          { name: "sortOrder", in: "query", schema: { type: "string", enum: ["asc", "desc"] } },
        ],
      },
    },
    "/emails/{id}": { get: { summary: "Detalle de correo" } },
    "/emails/{id}/classification": { patch: { summary: "Corregir clasificacion" } },
    "/emails/{id}/mark-reviewed": { post: { summary: "Marcar correo revisado" } },
    "/emails/{id}/mark-important": { post: { summary: "Marcar correo importante" } },
    "/alerts": { get: { summary: "Listar alertas" } },
    "/alerts/{id}": { get: { summary: "Detalle de alerta" } },
    "/alerts/{id}/resolve": { post: { summary: "Resolver alerta" } },
    "/alerts/{id}/ignore": { post: { summary: "Ignorar alerta" } },
    "/senders": { get: { summary: "Listar remitentes" } },
    "/senders/{id}": { get: { summary: "Detalle de remitente" } },
    "/senders/{id}/trust": { post: { summary: "Marcar remitente confiable" } },
    "/senders/{id}/suspicious": { post: { summary: "Marcar remitente sospechoso" } },
    "/senders/{id}/emails": { get: { summary: "Correos de remitente" } },
    "/rules": {
      get: { summary: "Listar reglas" },
      post: { summary: "Crear regla" },
    },
    "/rules/{id}": {
      get: { summary: "Detalle de regla" },
      patch: { summary: "Actualizar regla" },
      delete: { summary: "Eliminar regla" },
    },
    "/rules/{id}/enable": { post: { summary: "Activar regla" } },
    "/rules/{id}/disable": { post: { summary: "Desactivar regla" } },
    "/analytics/summary": { get: { summary: "Resumen analitico" } },
    "/analytics/emails-by-day": { get: { summary: "Correos por dia" } },
    "/analytics/categories": { get: { summary: "Distribucion por categoria" } },
    "/analytics/top-senders": { get: { summary: "Top remitentes" } },
    "/analytics/accounts": { get: { summary: "Analitica por cuenta Gmail" } },
    "/audit": { get: { summary: "Auditoria" } },
    "/settings": {
      get: { summary: "Obtener configuracion" },
      patch: { summary: "Actualizar configuracion" },
    },
  },
} as const;

